### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by mizumizue** [kawamou/my-layered-architecture#1]
# 概要

Code Review用のIssueです。
気になった箇所をコメントでぶら下げていきます。

## アーキテクチャ図参考
<img width="242" alt="スクリーンショット 2021-09-29 16 58 03" src="https://user-images.githubusercontent.com/26603341/135229700-bdd11c91-1257-4bbe-86e8-577d1b858ada.png">
出典: [pospomeのサーバサイドアーキテクチャ](https://booth.pm/ja/items/1045782)

**Comment by mizumizue** [comment]
https://github.com/kawamou/my-layered-architecture/blob/fee8c41fe9b6cff4293e754769a7521fb1501750/main.go#L10
```
const port string = ":8080"
```

アーキテクチャと関係ない箇所ですが、環境変数から取るようにするとインフラに依存しなくなるかと思います！

**Comment by mizumizue** [comment]
https://github.com/kawamou/my-layered-architecture/blob/fee8c41fe9b6cff4293e754769a7521fb1501750/infra/firestore.go#L12
関数内部で動作の停止する `log.Fatal` はあまり好ましくないかなと思います。
error は呼び出し元へ返し、そこで処理する（停止するにしても）がGoらしい書き方かなと思います

**Comment by mizumizue** [comment]
DIは[Wire](https://github.com/google/wire)がおすすめです！

手前味噌ですが、Wireを使ってDIをしているコードサンプルもありますので、よろしければどうぞ
https://github.com/mizumizue/clean-architecture-go/blob/c234598c9e65ad9e9f6dabf442c30334555d0a7d/src/infrastructure/waf/echo/router/router.go#L30

**Comment by mizumizue** [comment]
https://github.com/kawamou/my-layered-architecture/blob/fee8c41fe9b6cff4293e754769a7521fb1501750/infra/user_repository_impl.go#L31
LayeredArchitectureではDomain->Infrastructureへの依存は許されている一方で、Infrastructure→Domainの依存は許されておらず、依存関係が逆転してしまっているかと思います。

この場合、RepositoryではDtoを返し、ApplicationServiceにて、Domainのモデルに詰め替えることになるかと思います

**Comment by kawamou** [comment]
> https://github.com/kawamou/my-layered-architecture/blob/fee8c41fe9b6cff4293e754769a7521fb1501750/infra/user_repository_impl.go#L31
> 
> 
> LayeredArchitectureではDomain->Infrastructureへの依存は許されている一方で、Infrastructure→Domainの依存は許されておらず、依存関係が逆転してしまっているかと思います。
> この場合、RepositoryではDtoを返し、ApplicationServiceにて、Domainのモデルに詰め替えることになるかと思います

こちら自分がレイヤードアーキテクチャと明記してるのが良くないですね...。
イメージは"layeredish"なアーキテクチャを想定してました！
インフラ層だけ逆転させる感じです。
このイメージです！
https://speakerdeck.com/hgsgtk/go-api-architecture-practical-example?slide=6
